export const GET_ENCLOSURE = "GET_ENCLOSURE";
export const LOAD_ENCLOSURES = "LOAD_ENCLOSURES";
export const POST_ENCLOSURE = "POST_ENCLOSURE";
export const PATCH_ENCLOSURE = "PATCH_ENCLOSURE";
export const DELETE_ENCLOSURE = "DELETE_ENCLOSURE";
export const POST_ANIMAL_TO_ENCLOSURE = "POST_ANIMAL_TO_ENCLOSURE";
export const DELETE_ANIMAL_FROM_ENCLOSURE = "DELETE_ANIMAL_FROM_ENCLOSURE";














export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";