export const GET_ENCLOSURE = "GET_ENCLOSURE";
export const LOAD_ENCLOSURES = "LOAD_ENCLOSURES";
export const POST_ENCLOSURE = "POST_ENCLOSURE";
export const PATCH_ENCLOSURE = "PATCH_ENCLOSURE";
export const DELETE_ENCLOSURE = "DELETE_ENCLOSURE";
export const POST_ANIMAL_TO_ENCLOSURE = "POST_ANIMAL_TO_ENCLOSURE";
export const DELETE_ANIMAL_FROM_ENCLOSURE = "DELETE_ANIMAL_FROM_ENCLOSURE";


export const GET_ANIMAL = "GET_ANIMAL";
export const LOAD_ANIMALS = "LOAD_ANIMALS";
export const POST_ANIMAL = "POST_ANIMAL";
export const PATCH_ANIMAL = "PATCH_ANIMAL";
export const DELETE_ANIMAL = "DELETE_ANIMAL";











export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";